### ISSUE TITLE
Failed to export Microsoft Excel file

### ISSUE THREAD

**Issue by Darkelyzed** [3dcitydb/plugin-spreadsheet-generator#3]
so i tried to export the data to Microsoft excel format, but it failed.

`java.lang.NullPointerException
	at org.citydb.plugins.spreadsheet_gen.controller.SpreadsheetExporter.convertToXSLX(SpreadsheetExporter.java:325)
	at org.citydb.plugins.spreadsheet_gen.controller.SpreadsheetExporter.doProcess(SpreadsheetExporter.java:246)
	at org.citydb.plugins.spreadsheet_gen.gui.view.SPSHGPanel.doExport(SPSHGPanel.java:969)
	at org.citydb.plugins.spreadsheet_gen.gui.view.SPSHGPanel.access$100(SPSHGPanel.java:116)
	at org.citydb.plugins.spreadsheet_gen.gui.view.SPSHGPanel$2$1.run(SPSHGPanel.java:557)
`

I tried the other format, the csv and it worked

**Comment by yaozhihang** [comment]
Sorry for the nonresponse. We recently release a new major version of the 3DCityDB software suite, which can be obtained here:
https://github.com/3dcitydb/3dcitydb-suite/releases/tag/v2021.1.0

Hope this new version works well in your use cases. Feel free to reopen the ticket if you can still get the issue.
